services:
  - type: web
    name: image-accuracy-finder
    runtime: python
    repo: https://github.com/sankaroffzl/image-accuracy-finder
    branch: master
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    plan: free
    autoDeploy: yes
